name: CI/CD - Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      # Install Packages
      - name: Install
        run: npm install

      # Lint
      - name: Lint
        run: npm run lint

      # Build the website
      - name: Build
        run: npm run build:production

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          target: ${{ secrets.DEPLOYMENT_LOCATION }}
