name: Reflecta Mono - Develop Build & Deploy

on:
  push:
    branches: [develop]
    paths: ['./**', '!packages/**']
  pull_request:
    branches: [develop]
    paths: ['./**', '!packages/**']
  workflow_dispatch:
    branches: [develop]
    paths: ['./**', '!packages/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm install

      # Lint
      - name: Lint
        run: npm run lint --workspaces

      # Build Packages
      - name: Build
        run: npm run build:develop --workspaces
