name: Reflecta UI - Build & Deploy

on:
  push:
    branches: [main, develop]
    paths: [packages/reflecta-ui/**]
  workflow_dispatch:
    branches: [main, develop]
    paths: [packages/reflecta-ui/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm install

      # Build Dependencies
      - name: Build Dependencies
        run: npm run build -w reflecta-components

      # Lint
      - name: Lint
        run: npm run lint -w reflecta-ui

      # Build Reflecta UI
      - name: Build
        run: npm run build -w reflecta-ui
        env:
          FEDERATED_COMPONENTS_URL: ${{ vars.FEDERATED_COMPONENTS_URL }}
          NODE_ENV: ${{ vars.NODE_ENV}}
          WEBPACK_SERVER_PORT_COMPONENTS: ${{ vars.WEBPACK_SERVER_PORT_COMPONENTS}}

      # Deploy Reflecta UI
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "./packages/reflecta-ui/dist/*"
          strip_components: 3
          target: ${{ vars.DEPLOYMENT_LOCATION_COMPONENTS }}
          timeout: "120s"
          username: ${{ secrets.USERNAME }}
          overwrite: true
