name: Reflecta Components - Build & Deploy

on:
  push:
    branches: [main, develop]
    paths: [packages/reflecta-components/**]
  workflow_dispatch:
    branches: [main, develop]
    paths: [packages/reflecta-components/**]

jobs:
  lint-scss:
    name: Lint SCSS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint SCSS
      - name: Lint
        run: npm run lint:scss -w reflecta-components

  lint-js:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint JavaScript/TypeScript
      - name: Lint
        run: npm run lint:js -w reflecta-components

  build-mf:
    name: Build Module Federation Bundle
    needs: [lint-scss, lint-js]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Build Reflecta Components
      - name: Build
        run: npm run build -w reflecta-components
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          WEBPACK_SERVER_PORT_COMPONENTS: ${{ env.WEBPACK_SERVER_PORT_COMPONENTS }}

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./packages/reflecta-components/dist/

  build-storybook:
    name: Build Storybook
    needs: [lint-scss, lint-js]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Build Storybook Bundle
      - name: Build
        run: npm run build:storybook -w reflecta-components

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./packages/reflecta-components/storybook-static/

  deploy:
    name: Deploy
    needs: [build-mf, build-storybook]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      # Deploy Reflecta Components
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "./bundle/*"
          strip_components: 1
          target: ${{ vars.DEPLOYMENT_LOCATION_COMPONENTS }}
          timeout: "120s"
          username: ${{ secrets.USERNAME }}
          overwrite: true
