name: Reflecta UI - Build & Deploy

on:
  push:
    branches: [main, develop]
    paths: [packages/reflecta-ui/**]
  workflow_dispatch:
    branches: [main, develop]
    paths: [packages/reflecta-ui/**]

jobs:
  lint-scss:
    name: Lint SCSS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install Node Modules
      - name: Install
        run: npm ci --legacy-peers-deps

      # Lint SCSS
      - name: Lint
        run: npm run lint:scss -w reflecta-ui

  lint-js:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install Node Modules
      - name: Install
        run: npm ci --legacy-peers-deps

      # Lint JavaScript/TypeScript
      - name: Lint
        run: npm run lint:js -w reflecta-ui

  build-components:
    name: Build Components
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install Node Modules
      - name: Install
        run: npm ci --legacy-peers-deps

      # Build Reflecta ui
      - name: Build
        run: npm run build -w reflecta-components
        env:
          NODE_ENV: ${{ vars.NODE_ENV}}

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: component-declarations
          path: ./packages/reflecta-components/declarations/

  build:
    name: Build
    needs: [lint-scss, lint-js, build-components]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install Node Modules
      - name: Install
        run: npm ci --legacy-peers-deps

      # Download Artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: component-declarations
          path: ./packages/reflecta-components/declarations/

      # Build Reflecta UI
      - name: Build
        run: npm run build -w reflecta-ui
        env:
          BASE_URL_API: ${{ vars.BASE_URL_API }}
          FEDERATED_COMPONENTS_URL: ${{ vars.FEDERATED_COMPONENTS_URL }}
          LOCAL_STORAGE_AUTHENTICATION_TOKEN_KEY: ${{ vars.LOCAL_STORAGE_AUTHENTICATION_TOKEN_KEY }}
          NODE_ENV: ${{ vars.NODE_ENV }}

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ./packages/reflecta-ui/dist/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      # Download Artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      # Deploy Reflecta ui
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "./bundle/*"
          strip_components: 1
          target: ${{ vars.DEPLOYMENT_LOCATION_UI }}
          timeout: "120s"
          username: ${{ secrets.USERNAME }}
          overwrite: true
