name: Reflecta Components - Build & Deploy

on:
  push:
    branches: [main, develop]
    paths: [packages/reflecta-components/**]
  workflow_dispatch:
    branches: [main, develop]
    paths: [packages/reflecta-components/**]

jobs:
  lint-scss:
    name: Lint SCSS
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint SCSS
      - name: Lint
        run: npm run lint:scss -w reflecta-components

  lint-js:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint JavaScript/TypeScript
      - name: Lint
        run: npm run lint:js -w reflecta-components

  build-components:
    name: Build
    needs: [lint-scss, lint-js]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Build Reflecta Components
      - name: Build
        run: npm run build -w reflecta-components
        env:
          NODE_ENV: ${{ vars.NODE_ENV}}
          WEBPACK_SERVER_PORT_COMPONENTS: ${{ env.WEBPACK_SERVER_PORT_COMPONENTS}}

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./packages/reflecta-components/dist/


  build:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R
