name: Reflecta Components - Build & Deploy

on:
  push:
    branches: [main, develop]
    paths: [packages/reflecta-components/**]
  workflow_dispatch:
    branches: [main, develop]
    paths: [packages/reflecta-components/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm install

      # Lint
      - name: Lint
        run: npm run lint -w reflecta-components

      # Build Reflecta Components
      - name: Build
        run: npm run build -w reflecta-components

      # Deploy Reflecta Components
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "./packages/reflecta-components/dist/*"
          strip_components: 3
          target: ${{ env.DEPLOYMENT_LOCATION_COMPONENTS }}
          timeout: "120s"
          username: ${{ secrets.USERNAME }}
          overwrite: true
