name: Reflecta Backend - Build & Deploy

on:
  push:
    branches: [main, develop]
    paths: [packages/reflecta-backend/**]
  workflow_dispatch:
    branches: [main, develop]
    paths: [packages/reflecta-backend/**]

jobs:
  lint:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint JavaScript/TypeScript
      - name: Lint
        run: npm run lint -w reflecta-backend

  bundle:
    name: Bundle
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      # Install Node Modules
      - name: Install
        run: npm ci

      # Compile TypeScript
      - name: Build
        run: npm run build -w reflecta-backend

      # Install Production Packages
      - name: Install Production Packages
        run: npm ci --ignore-scripts -w reflecta-backend

      # Copy Packages
      - name: Copy Packages Config
        run: |
          cp -r ./node_modules/ ./packages/reflecta-backend/dist/
          cp ./packages/reflecta-backend/package.json ./packages/reflecta-backend/dist/

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./packages/reflecta-backend/dist/

  deploy:
    name: Deploy
    needs: [bundle]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      # Deploy Backend
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "./bundle/*"
          strip_components: 1
          target: ${{ vars.DEPLOYMENT_LOCATION_BACKEND }}
          timeout: "120s"
          username: ${{ secrets.USERNAME }}
          overwrite: true
