name: Reflecta Components - Lint

on:
  push:
    branches: ['*', '!develop', '!main']
    paths: [packages/reflecta-components/**]
  workflow_dispatch:
    branches: ['*', '!develop', '!main']
    paths: [packages/reflecta-components/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm install

      # Lint
      - name: Lint
        run: npm run lint -w reflecta-components
