name: Reflecta Backend - Build & Deploy

on:
  push:
    branches: [main, develop]
    paths:
      - packages/reflecta-backend/**
      - .github/**
  workflow_dispatch:
    branches: [main, develop]
    paths: [packages/reflecta-backend/**]

jobs:
  lint:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install Node Modules
      - name: Install
        run: npm ci --legacy-peers-deps

      # Lint JavaScript/TypeScript
      - name: Lint
        run: npm run lint -w reflecta-backend

  bundle:
    name: Bundle
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install Node Modules
      - name: Install
        run: npm ci --legacy-peers-deps

      # Compile TypeScript
      - name: Build
        run: npm run build -w reflecta-backend

      # Install Production Packages
      - name: Install Production Packages
        run: npm ci --legacy-peers-deps --only-production --ignore-scripts -w reflecta-backend

      # Install Production Packages
      - name: Fully Install bcrypt
        run: npm explore bcrypt -- npm install

      # Copy Packages
      - name: Copy Packages Config
        run: |
          cp -r ./node_modules/ ./packages/reflecta-backend/dist/
          cp ./packages/reflecta-backend/package.json ./packages/reflecta-backend/dist/

      # Zip Artifact
      - name: Zip Artifact
        run: zip bundle.zip ./packages/reflecta-backend/dist/* -r

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ./bundle.zip

  deploy:
    name: Deploy
    needs: [bundle]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: bundle

      # Unzip Artifact
      - name: Unzip Artifact
        run: unzip ./bundle.zip

      # Deploy Backend
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "./packages/reflecta-backend/dist/*"
          strip_components: 3
          target: ${{ vars.DEPLOYMENT_LOCATION_BACKEND }}
          timeout: "120s"
          username: ${{ secrets.USERNAME }}
          overwrite: true
