name: Reflecta Backend - Lint

on:
  push:
    branches: ['*', '!develop', '!main']
    paths: [packages/reflecta-backend/**]
  workflow_dispatch:
    branches: ['*', '!develop', '!main']
    paths: [packages/reflecta-backend/**]

jobs:
  lint:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint JavaScript/TypeScript
      - name: Lint
        run: npm run lint -w reflecta-backend
