name: Reflecta UI - Lint

on:
  push:
    branches: ['*', '!develop', '!main']
    paths: [packages/reflecta-ui/**]
  workflow_dispatch:
    branches: ['*', '!develop', '!main']
    paths: [packages/reflecta-ui/**]

jobs:
  lint-scss:
    name: Lint SCSS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint SCSS
      - name: Lint
        run: npm run lint:scss -w reflecta-ui

  lint-js:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint JavaScript/TypeScript
      - name: Lint
        run: npm run lint:js -w reflecta-ui
