name: Reflecta UI - Develop Build & Deploy

on:
  push:
    branches: [develop]
    paths: [packages/reflecta-ui/**]
  pull_request:
    branches: [develop]
    paths: [packages/reflecta-ui/**]
  workflow_dispatch:
    branches: [develop]
    paths: [packages/reflecta-ui/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm install

      # Build Dependencies
      - name: Build Dependencies
        run: npm run build:production -w reflecta-components

      # Lint
      - name: Lint
        run: npm run lint -w reflecta-ui

      # Build Reflecta UI
      - name: Build
        run: npm run build:develop -w reflecta-ui
