name: Reflecta UI - Build & Deploy

on:
  push:
    branches: [main, develop]
    paths: [packages/reflecta-ui/**]
  workflow_dispatch:
    branches: [main, develop]
    paths: [packages/reflecta-ui/**]

jobs:
  lint-scss:
    name: Lint SCSS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint SCSS
      - name: Lint
        run: npm run lint:scss -w reflecta-ui

  lint-js:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Lint JavaScript/TypeScript
      - name: Lint
        run: npm run lint:js -w reflecta-ui

  build-components:
    name: Build Components
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Build Reflecta ui
      - name: Build
        run: npm run build -w reflecta-components
        env:
          NODE_ENV: ${{ vars.NODE_ENV}}
          WEBPACK_SERVER_PORT_ui: ${{ env.WEBPACK_SERVER_PORT_COMPONENTS}}

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ./packages/reflecta-components/dist/
          path: ./packages/reflecta-components/dist/

  build:
    name: Build
    needs: [lint-scss, lint-js, build-components]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm ci

      # Download Artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      # Build Reflecta UI
      - name: Build
        run: npm run build -w reflecta-ui
        env:
          NODE_ENV: ${{ vars.NODE_ENV}}
          WEBPACK_SERVER_PORT_ui: ${{ env.WEBPACK_SERVER_PORT_UI}}

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./packages/reflecta-ui/dist/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      # Download Artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      # Deploy Reflecta ui
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "./bundle/*"
          strip_ui: 1
          target: ${{ vars.DEPLOYMENT_LOCATION_UI }}
          timeout: "120s"
          username: ${{ secrets.USERNAME }}
          overwrite: true
