name: Reflecta UI - Production Build & Deploy

on:
  push:
    branches: [main]
    paths: [packages/reflecta-ui/**]
  pull_request:
    branches: [main]
    paths: [packages/reflecta-ui/**]
  workflow_dispatch:
    branches: [main]
    paths: [packages/reflecta-ui/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use NodeJS 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      # Install Node Modules
      - name: Install
        run: npm install

      # Lint
      - name: Lint
        run: npm run lint -w reflecta-ui

      # Build Reflecta UI
      - name: Build
        run: npm run build:production -w reflecta-ui

      # Deploy Reflecta UI
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "./packages/reflecta-ui/dist/*"
          strip_components: 3
          target: ${{ secrets.DEPLOYMENT_LOCATION }}
          timeout: "120s"
          username: ${{ secrets.USERNAME }}
          overwrite: true
